// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "api/api.proto",
    "version": "version not set"
  },
  "paths": {
    "/v1/set_answer/{userId}": {
      "post": {
        "tags": [
          "ICHSurvey"
        ],
        "operationId": "ICHSurvey_SetAnswer",
        "parameters": [
          {
            "type": "string",
            "format": "uint64",
            "name": "userId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ICHSurveySetAnswerBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/apiQuestionResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        }
      }
    },
    "/v1/start_survey/{userId}": {
      "get": {
        "tags": [
          "ICHSurvey"
        ],
        "operationId": "ICHSurvey_StartSurvey",
        "parameters": [
          {
            "type": "string",
            "format": "uint64",
            "name": "userId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/apiQuestionResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ICHSurveySetAnswerBody": {
      "type": "object",
      "properties": {
        "answer": {
          "type": "string"
        },
        "number": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "apiClassQuestions": {
      "type": "string",
      "default": "UNKNOWN_QUESTIONS_CLASS",
      "enum": [
        "UNKNOWN_QUESTIONS_CLASS",
        "LINUX_QUESTIONS",
        "K8S_QUESTIONS",
        "NETWORK_QUESTIONS",
        "SECURITY_QUESTIONS",
        "CONTAINER_QUESTIONS",
        "DEVELOPER_UESTIONS"
      ]
    },
    "apiQuestionResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "number": {
          "type": "integer",
          "format": "int64"
        },
        "question": {
          "type": "string"
        },
        "userId": {
          "type": "string",
          "format": "uint64"
        }
      }
    },
    "apiStatusResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "apiSurvey": {
      "type": "object",
      "properties": {
        "answer": {
          "type": "string"
        },
        "latency": {
          "type": "string"
        },
        "number": {
          "type": "integer",
          "format": "int64"
        },
        "question": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "userId": {
          "type": "string",
          "format": "uint64"
        }
      }
    },
    "apiSurveyResponse": {
      "type": "object",
      "properties": {
        "mesage": {
          "type": "string"
        },
        "qs": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/apiSurvey"
          }
        },
        "startSurvey": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "details": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/protobufAny"
          }
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "name": "ICHSurvey"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "api/api.proto",
    "version": "version not set"
  },
  "paths": {
    "/v1/set_answer/{userId}": {
      "post": {
        "tags": [
          "ICHSurvey"
        ],
        "operationId": "ICHSurvey_SetAnswer",
        "parameters": [
          {
            "type": "string",
            "format": "uint64",
            "name": "userId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ICHSurveySetAnswerBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/apiQuestionResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        }
      }
    },
    "/v1/start_survey/{userId}": {
      "get": {
        "tags": [
          "ICHSurvey"
        ],
        "operationId": "ICHSurvey_StartSurvey",
        "parameters": [
          {
            "type": "string",
            "format": "uint64",
            "name": "userId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/apiQuestionResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ICHSurveySetAnswerBody": {
      "type": "object",
      "properties": {
        "answer": {
          "type": "string"
        },
        "number": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "apiClassQuestions": {
      "type": "string",
      "default": "UNKNOWN_QUESTIONS_CLASS",
      "enum": [
        "UNKNOWN_QUESTIONS_CLASS",
        "LINUX_QUESTIONS",
        "K8S_QUESTIONS",
        "NETWORK_QUESTIONS",
        "SECURITY_QUESTIONS",
        "CONTAINER_QUESTIONS",
        "DEVELOPER_UESTIONS"
      ]
    },
    "apiQuestionResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "number": {
          "type": "integer",
          "format": "int64"
        },
        "question": {
          "type": "string"
        },
        "userId": {
          "type": "string",
          "format": "uint64"
        }
      }
    },
    "apiStatusResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "apiSurvey": {
      "type": "object",
      "properties": {
        "answer": {
          "type": "string"
        },
        "latency": {
          "type": "string"
        },
        "number": {
          "type": "integer",
          "format": "int64"
        },
        "question": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "userId": {
          "type": "string",
          "format": "uint64"
        }
      }
    },
    "apiSurveyResponse": {
      "type": "object",
      "properties": {
        "mesage": {
          "type": "string"
        },
        "qs": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/apiSurvey"
          }
        },
        "startSurvey": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "details": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/protobufAny"
          }
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "name": "ICHSurvey"
    }
  ]
}`))
}
