// Code generated by go-swagger; DO NOT EDIT.

package i_c_h_survey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/lixoi/survey/models"
)

// ICHSurveyStartSurveyOKCode is the HTTP code returned for type ICHSurveyStartSurveyOK
const ICHSurveyStartSurveyOKCode int = 200

/*
ICHSurveyStartSurveyOK A successful response.

swagger:response iCHSurveyStartSurveyOK
*/
type ICHSurveyStartSurveyOK struct {

	/*
	  In: Body
	*/
	Payload *models.APIQuestionResponse `json:"body,omitempty"`
}

// NewICHSurveyStartSurveyOK creates ICHSurveyStartSurveyOK with default headers values
func NewICHSurveyStartSurveyOK() *ICHSurveyStartSurveyOK {

	return &ICHSurveyStartSurveyOK{}
}

// WithPayload adds the payload to the i c h survey start survey o k response
func (o *ICHSurveyStartSurveyOK) WithPayload(payload *models.APIQuestionResponse) *ICHSurveyStartSurveyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the i c h survey start survey o k response
func (o *ICHSurveyStartSurveyOK) SetPayload(payload *models.APIQuestionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ICHSurveyStartSurveyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ICHSurveyStartSurveyDefault An unexpected error response.

swagger:response iCHSurveyStartSurveyDefault
*/
type ICHSurveyStartSurveyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.RPCStatus `json:"body,omitempty"`
}

// NewICHSurveyStartSurveyDefault creates ICHSurveyStartSurveyDefault with default headers values
func NewICHSurveyStartSurveyDefault(code int) *ICHSurveyStartSurveyDefault {
	if code <= 0 {
		code = 500
	}

	return &ICHSurveyStartSurveyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the i c h survey start survey default response
func (o *ICHSurveyStartSurveyDefault) WithStatusCode(code int) *ICHSurveyStartSurveyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the i c h survey start survey default response
func (o *ICHSurveyStartSurveyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the i c h survey start survey default response
func (o *ICHSurveyStartSurveyDefault) WithPayload(payload *models.RPCStatus) *ICHSurveyStartSurveyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the i c h survey start survey default response
func (o *ICHSurveyStartSurveyDefault) SetPayload(payload *models.RPCStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ICHSurveyStartSurveyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
