// Code generated by go-swagger; DO NOT EDIT.

package i_c_h_survey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/lixoi/survey/models"
)

// ICHSurveySetAnswerOKCode is the HTTP code returned for type ICHSurveySetAnswerOK
const ICHSurveySetAnswerOKCode int = 200

/*
ICHSurveySetAnswerOK A successful response.

swagger:response iCHSurveySetAnswerOK
*/
type ICHSurveySetAnswerOK struct {

	/*
	  In: Body
	*/
	Payload *models.APIQuestionResponse `json:"body,omitempty"`
}

// NewICHSurveySetAnswerOK creates ICHSurveySetAnswerOK with default headers values
func NewICHSurveySetAnswerOK() *ICHSurveySetAnswerOK {

	return &ICHSurveySetAnswerOK{}
}

// WithPayload adds the payload to the i c h survey set answer o k response
func (o *ICHSurveySetAnswerOK) WithPayload(payload *models.APIQuestionResponse) *ICHSurveySetAnswerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the i c h survey set answer o k response
func (o *ICHSurveySetAnswerOK) SetPayload(payload *models.APIQuestionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ICHSurveySetAnswerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ICHSurveySetAnswerDefault An unexpected error response.

swagger:response iCHSurveySetAnswerDefault
*/
type ICHSurveySetAnswerDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.RPCStatus `json:"body,omitempty"`
}

// NewICHSurveySetAnswerDefault creates ICHSurveySetAnswerDefault with default headers values
func NewICHSurveySetAnswerDefault(code int) *ICHSurveySetAnswerDefault {
	if code <= 0 {
		code = 500
	}

	return &ICHSurveySetAnswerDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the i c h survey set answer default response
func (o *ICHSurveySetAnswerDefault) WithStatusCode(code int) *ICHSurveySetAnswerDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the i c h survey set answer default response
func (o *ICHSurveySetAnswerDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the i c h survey set answer default response
func (o *ICHSurveySetAnswerDefault) WithPayload(payload *models.RPCStatus) *ICHSurveySetAnswerDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the i c h survey set answer default response
func (o *ICHSurveySetAnswerDefault) SetPayload(payload *models.RPCStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ICHSurveySetAnswerDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
