// Code generated by go-swagger; DO NOT EDIT.

package i_c_h_survey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/lixoi/survey/models"
)

// ICHSurveySetAnswerReader is a Reader for the ICHSurveySetAnswer structure.
type ICHSurveySetAnswerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ICHSurveySetAnswerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewICHSurveySetAnswerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewICHSurveySetAnswerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewICHSurveySetAnswerOK creates a ICHSurveySetAnswerOK with default headers values
func NewICHSurveySetAnswerOK() *ICHSurveySetAnswerOK {
	return &ICHSurveySetAnswerOK{}
}

/*
ICHSurveySetAnswerOK describes a response with status code 200, with default header values.

A successful response.
*/
type ICHSurveySetAnswerOK struct {
	Payload *models.APIQuestionResponse
}

// IsSuccess returns true when this i c h survey set answer o k response has a 2xx status code
func (o *ICHSurveySetAnswerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this i c h survey set answer o k response has a 3xx status code
func (o *ICHSurveySetAnswerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this i c h survey set answer o k response has a 4xx status code
func (o *ICHSurveySetAnswerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this i c h survey set answer o k response has a 5xx status code
func (o *ICHSurveySetAnswerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this i c h survey set answer o k response a status code equal to that given
func (o *ICHSurveySetAnswerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the i c h survey set answer o k response
func (o *ICHSurveySetAnswerOK) Code() int {
	return 200
}

func (o *ICHSurveySetAnswerOK) Error() string {
	return fmt.Sprintf("[POST /v1/set_answer/{userId}][%d] iCHSurveySetAnswerOK  %+v", 200, o.Payload)
}

func (o *ICHSurveySetAnswerOK) String() string {
	return fmt.Sprintf("[POST /v1/set_answer/{userId}][%d] iCHSurveySetAnswerOK  %+v", 200, o.Payload)
}

func (o *ICHSurveySetAnswerOK) GetPayload() *models.APIQuestionResponse {
	return o.Payload
}

func (o *ICHSurveySetAnswerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIQuestionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewICHSurveySetAnswerDefault creates a ICHSurveySetAnswerDefault with default headers values
func NewICHSurveySetAnswerDefault(code int) *ICHSurveySetAnswerDefault {
	return &ICHSurveySetAnswerDefault{
		_statusCode: code,
	}
}

/*
ICHSurveySetAnswerDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ICHSurveySetAnswerDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this i c h survey set answer default response has a 2xx status code
func (o *ICHSurveySetAnswerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this i c h survey set answer default response has a 3xx status code
func (o *ICHSurveySetAnswerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this i c h survey set answer default response has a 4xx status code
func (o *ICHSurveySetAnswerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this i c h survey set answer default response has a 5xx status code
func (o *ICHSurveySetAnswerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this i c h survey set answer default response a status code equal to that given
func (o *ICHSurveySetAnswerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the i c h survey set answer default response
func (o *ICHSurveySetAnswerDefault) Code() int {
	return o._statusCode
}

func (o *ICHSurveySetAnswerDefault) Error() string {
	return fmt.Sprintf("[POST /v1/set_answer/{userId}][%d] ICHSurvey_SetAnswer default  %+v", o._statusCode, o.Payload)
}

func (o *ICHSurveySetAnswerDefault) String() string {
	return fmt.Sprintf("[POST /v1/set_answer/{userId}][%d] ICHSurvey_SetAnswer default  %+v", o._statusCode, o.Payload)
}

func (o *ICHSurveySetAnswerDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ICHSurveySetAnswerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
