// Code generated by go-swagger; DO NOT EDIT.

package i_c_h_survey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/lixoi/survey/models"
)

// NewICHSurveySetAnswerParams creates a new ICHSurveySetAnswerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewICHSurveySetAnswerParams() *ICHSurveySetAnswerParams {
	return &ICHSurveySetAnswerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewICHSurveySetAnswerParamsWithTimeout creates a new ICHSurveySetAnswerParams object
// with the ability to set a timeout on a request.
func NewICHSurveySetAnswerParamsWithTimeout(timeout time.Duration) *ICHSurveySetAnswerParams {
	return &ICHSurveySetAnswerParams{
		timeout: timeout,
	}
}

// NewICHSurveySetAnswerParamsWithContext creates a new ICHSurveySetAnswerParams object
// with the ability to set a context for a request.
func NewICHSurveySetAnswerParamsWithContext(ctx context.Context) *ICHSurveySetAnswerParams {
	return &ICHSurveySetAnswerParams{
		Context: ctx,
	}
}

// NewICHSurveySetAnswerParamsWithHTTPClient creates a new ICHSurveySetAnswerParams object
// with the ability to set a custom HTTPClient for a request.
func NewICHSurveySetAnswerParamsWithHTTPClient(client *http.Client) *ICHSurveySetAnswerParams {
	return &ICHSurveySetAnswerParams{
		HTTPClient: client,
	}
}

/*
ICHSurveySetAnswerParams contains all the parameters to send to the API endpoint

	for the i c h survey set answer operation.

	Typically these are written to a http.Request.
*/
type ICHSurveySetAnswerParams struct {

	// Body.
	Body *models.ICHSurveySetAnswerBody

	// UserID.
	//
	// Format: uint64
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the i c h survey set answer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ICHSurveySetAnswerParams) WithDefaults() *ICHSurveySetAnswerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the i c h survey set answer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ICHSurveySetAnswerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the i c h survey set answer params
func (o *ICHSurveySetAnswerParams) WithTimeout(timeout time.Duration) *ICHSurveySetAnswerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the i c h survey set answer params
func (o *ICHSurveySetAnswerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the i c h survey set answer params
func (o *ICHSurveySetAnswerParams) WithContext(ctx context.Context) *ICHSurveySetAnswerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the i c h survey set answer params
func (o *ICHSurveySetAnswerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the i c h survey set answer params
func (o *ICHSurveySetAnswerParams) WithHTTPClient(client *http.Client) *ICHSurveySetAnswerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the i c h survey set answer params
func (o *ICHSurveySetAnswerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the i c h survey set answer params
func (o *ICHSurveySetAnswerParams) WithBody(body *models.ICHSurveySetAnswerBody) *ICHSurveySetAnswerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the i c h survey set answer params
func (o *ICHSurveySetAnswerParams) SetBody(body *models.ICHSurveySetAnswerBody) {
	o.Body = body
}

// WithUserID adds the userID to the i c h survey set answer params
func (o *ICHSurveySetAnswerParams) WithUserID(userID string) *ICHSurveySetAnswerParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the i c h survey set answer params
func (o *ICHSurveySetAnswerParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *ICHSurveySetAnswerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
