// Code generated by go-swagger; DO NOT EDIT.

package i_c_h_survey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewICHSurveyStartSurveyParams creates a new ICHSurveyStartSurveyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewICHSurveyStartSurveyParams() *ICHSurveyStartSurveyParams {
	return &ICHSurveyStartSurveyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewICHSurveyStartSurveyParamsWithTimeout creates a new ICHSurveyStartSurveyParams object
// with the ability to set a timeout on a request.
func NewICHSurveyStartSurveyParamsWithTimeout(timeout time.Duration) *ICHSurveyStartSurveyParams {
	return &ICHSurveyStartSurveyParams{
		timeout: timeout,
	}
}

// NewICHSurveyStartSurveyParamsWithContext creates a new ICHSurveyStartSurveyParams object
// with the ability to set a context for a request.
func NewICHSurveyStartSurveyParamsWithContext(ctx context.Context) *ICHSurveyStartSurveyParams {
	return &ICHSurveyStartSurveyParams{
		Context: ctx,
	}
}

// NewICHSurveyStartSurveyParamsWithHTTPClient creates a new ICHSurveyStartSurveyParams object
// with the ability to set a custom HTTPClient for a request.
func NewICHSurveyStartSurveyParamsWithHTTPClient(client *http.Client) *ICHSurveyStartSurveyParams {
	return &ICHSurveyStartSurveyParams{
		HTTPClient: client,
	}
}

/*
ICHSurveyStartSurveyParams contains all the parameters to send to the API endpoint

	for the i c h survey start survey operation.

	Typically these are written to a http.Request.
*/
type ICHSurveyStartSurveyParams struct {

	// UserID.
	//
	// Format: uint64
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the i c h survey start survey params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ICHSurveyStartSurveyParams) WithDefaults() *ICHSurveyStartSurveyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the i c h survey start survey params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ICHSurveyStartSurveyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the i c h survey start survey params
func (o *ICHSurveyStartSurveyParams) WithTimeout(timeout time.Duration) *ICHSurveyStartSurveyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the i c h survey start survey params
func (o *ICHSurveyStartSurveyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the i c h survey start survey params
func (o *ICHSurveyStartSurveyParams) WithContext(ctx context.Context) *ICHSurveyStartSurveyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the i c h survey start survey params
func (o *ICHSurveyStartSurveyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the i c h survey start survey params
func (o *ICHSurveyStartSurveyParams) WithHTTPClient(client *http.Client) *ICHSurveyStartSurveyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the i c h survey start survey params
func (o *ICHSurveyStartSurveyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the i c h survey start survey params
func (o *ICHSurveyStartSurveyParams) WithUserID(userID string) *ICHSurveyStartSurveyParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the i c h survey start survey params
func (o *ICHSurveyStartSurveyParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *ICHSurveyStartSurveyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
