// Code generated by go-swagger; DO NOT EDIT.

package i_c_h_survey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/lixoi/survey/models"
)

// ICHSurveyStartSurveyReader is a Reader for the ICHSurveyStartSurvey structure.
type ICHSurveyStartSurveyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ICHSurveyStartSurveyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewICHSurveyStartSurveyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewICHSurveyStartSurveyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewICHSurveyStartSurveyOK creates a ICHSurveyStartSurveyOK with default headers values
func NewICHSurveyStartSurveyOK() *ICHSurveyStartSurveyOK {
	return &ICHSurveyStartSurveyOK{}
}

/*
ICHSurveyStartSurveyOK describes a response with status code 200, with default header values.

A successful response.
*/
type ICHSurveyStartSurveyOK struct {
	Payload *models.APIQuestionResponse
}

// IsSuccess returns true when this i c h survey start survey o k response has a 2xx status code
func (o *ICHSurveyStartSurveyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this i c h survey start survey o k response has a 3xx status code
func (o *ICHSurveyStartSurveyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this i c h survey start survey o k response has a 4xx status code
func (o *ICHSurveyStartSurveyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this i c h survey start survey o k response has a 5xx status code
func (o *ICHSurveyStartSurveyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this i c h survey start survey o k response a status code equal to that given
func (o *ICHSurveyStartSurveyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the i c h survey start survey o k response
func (o *ICHSurveyStartSurveyOK) Code() int {
	return 200
}

func (o *ICHSurveyStartSurveyOK) Error() string {
	return fmt.Sprintf("[GET /v1/start_survey/{userId}][%d] iCHSurveyStartSurveyOK  %+v", 200, o.Payload)
}

func (o *ICHSurveyStartSurveyOK) String() string {
	return fmt.Sprintf("[GET /v1/start_survey/{userId}][%d] iCHSurveyStartSurveyOK  %+v", 200, o.Payload)
}

func (o *ICHSurveyStartSurveyOK) GetPayload() *models.APIQuestionResponse {
	return o.Payload
}

func (o *ICHSurveyStartSurveyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIQuestionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewICHSurveyStartSurveyDefault creates a ICHSurveyStartSurveyDefault with default headers values
func NewICHSurveyStartSurveyDefault(code int) *ICHSurveyStartSurveyDefault {
	return &ICHSurveyStartSurveyDefault{
		_statusCode: code,
	}
}

/*
ICHSurveyStartSurveyDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ICHSurveyStartSurveyDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this i c h survey start survey default response has a 2xx status code
func (o *ICHSurveyStartSurveyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this i c h survey start survey default response has a 3xx status code
func (o *ICHSurveyStartSurveyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this i c h survey start survey default response has a 4xx status code
func (o *ICHSurveyStartSurveyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this i c h survey start survey default response has a 5xx status code
func (o *ICHSurveyStartSurveyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this i c h survey start survey default response a status code equal to that given
func (o *ICHSurveyStartSurveyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the i c h survey start survey default response
func (o *ICHSurveyStartSurveyDefault) Code() int {
	return o._statusCode
}

func (o *ICHSurveyStartSurveyDefault) Error() string {
	return fmt.Sprintf("[GET /v1/start_survey/{userId}][%d] ICHSurvey_StartSurvey default  %+v", o._statusCode, o.Payload)
}

func (o *ICHSurveyStartSurveyDefault) String() string {
	return fmt.Sprintf("[GET /v1/start_survey/{userId}][%d] ICHSurvey_StartSurvey default  %+v", o._statusCode, o.Payload)
}

func (o *ICHSurveyStartSurveyDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ICHSurveyStartSurveyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
