// Code generated by go-swagger; DO NOT EDIT.

package i_c_h_survey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new i c h survey API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for i c h survey API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ICHSurveySetAnswer(params *ICHSurveySetAnswerParams, opts ...ClientOption) (*ICHSurveySetAnswerOK, error)

	ICHSurveyStartSurvey(params *ICHSurveyStartSurveyParams, opts ...ClientOption) (*ICHSurveyStartSurveyOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ICHSurveySetAnswer i c h survey set answer API
*/
func (a *Client) ICHSurveySetAnswer(params *ICHSurveySetAnswerParams, opts ...ClientOption) (*ICHSurveySetAnswerOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewICHSurveySetAnswerParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ICHSurvey_SetAnswer",
		Method:             "POST",
		PathPattern:        "/v1/set_answer/{userId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ICHSurveySetAnswerReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ICHSurveySetAnswerOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ICHSurveySetAnswerDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ICHSurveyStartSurvey i c h survey start survey API
*/
func (a *Client) ICHSurveyStartSurvey(params *ICHSurveyStartSurveyParams, opts ...ClientOption) (*ICHSurveyStartSurveyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewICHSurveyStartSurveyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ICHSurvey_StartSurvey",
		Method:             "GET",
		PathPattern:        "/v1/start_survey/{userId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ICHSurveyStartSurveyReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ICHSurveyStartSurveyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ICHSurveyStartSurveyDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
