// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APISurvey api survey
//
// swagger:model apiSurvey
type APISurvey struct {

	// answer
	Answer string `json:"answer,omitempty"`

	// latency
	Latency string `json:"latency,omitempty"`

	// number
	Number int64 `json:"number,omitempty"`

	// question
	Question string `json:"question,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this api survey
func (m *APISurvey) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api survey based on context it is used
func (m *APISurvey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APISurvey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APISurvey) UnmarshalBinary(b []byte) error {
	var res APISurvey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
