// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIQuestionResponse api question response
//
// swagger:model apiQuestionResponse
type APIQuestionResponse struct {

	// message
	Message string `json:"message,omitempty"`

	// number
	Number int64 `json:"number,omitempty"`

	// question
	Question string `json:"question,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this api question response
func (m *APIQuestionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api question response based on context it is used
func (m *APIQuestionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIQuestionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIQuestionResponse) UnmarshalBinary(b []byte) error {
	var res APIQuestionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
