// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ICHSurveySetAnswerBody i c h survey set answer body
//
// swagger:model ICHSurveySetAnswerBody
type ICHSurveySetAnswerBody struct {

	// answer
	Answer string `json:"answer,omitempty"`

	// number
	Number int64 `json:"number,omitempty"`
}

// Validate validates this i c h survey set answer body
func (m *ICHSurveySetAnswerBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this i c h survey set answer body based on context it is used
func (m *ICHSurveySetAnswerBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ICHSurveySetAnswerBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ICHSurveySetAnswerBody) UnmarshalBinary(b []byte) error {
	var res ICHSurveySetAnswerBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
